### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by aminbp** [SyafiqTermizi/waktu-solat#1]
I am getting this error 

>>> import solat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solat/__init__.py", line 1, in <module>
    from urllib.request import urlopen
ImportError: No module named request

I found a solution. The environment I used using python2. To ensure it worked, use 
pip3 install solat

**Comment by SyafiqTermizi** [comment]
From the error I see you are using python 2. This module only support python 3.
